services:
  - type: web
    name: week-1-assignment-api
    env: python
    plan: free
    buildCommand: pip install uv && uv pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: OPENAI_API_KEY
        sync: false
